2019-12-20 13:41:59 WARN  ConnectionUtil:23 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:293)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:108)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.utilities.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repositories.CustomerDAOImpl.checkCustomer(CustomerDAOImpl.java:129)
	at com.revature.Driver.main(Driver.java:26)
2019-12-20 21:18:52 WARN  ConnectionUtil:23 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: database "project0" does not exist
	at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:471)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:112)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.utilities.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repositories.CustomerDAOImpl.login(CustomerDAOImpl.java:123)
	at com.revature.Driver.main(Driver.java:38)
2019-12-20 21:39:53 WARN  ConnectionUtil:23 - Unable to obtain connection to database
org.postgresql.util.PSQLException: The connection attempt failed.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:152)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.utilities.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repositories.CustomerDAOImpl.login(CustomerDAOImpl.java:123)
	at com.revature.Driver.main(Driver.java:38)
Caused by: java.net.UnknownHostException: :5432
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at org.postgresql.core.PGStream.<init>(PGStream.java:62)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:76)
	... 13 more
2019-12-20 21:48:43 WARN  ConnectionUtil:23 - Unable to obtain connection to database
org.postgresql.util.PSQLException: FATAL: database "project0" does not exist
	at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:471)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:112)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
	at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
	at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
	at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
	at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:32)
	at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
	at org.postgresql.Driver.makeConnection(Driver.java:393)
	at org.postgresql.Driver.connect(Driver.java:267)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.utilities.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repositories.CustomerDAOImpl.login(CustomerDAOImpl.java:123)
	at com.revature.Driver.main(Driver.java:38)
2019-12-20 22:16:30 WARN  ConnectionUtil:23 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for postgresql://localhost:5432/mydatabase?currentSchema=project0
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.utilities.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repositories.CustomerDAOImpl.login(CustomerDAOImpl.java:123)
	at com.revature.Driver.main(Driver.java:38)
2019-12-20 22:17:19 WARN  ConnectionUtil:23 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for postgresql://localhost:5432/postgres?currentSchema=project0
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.utilities.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repositories.CustomerDAOImpl.login(CustomerDAOImpl.java:123)
	at com.revature.Driver.main(Driver.java:38)
2019-12-20 22:24:24 WARN  ConnectionUtil:23 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for postgresql://localhost:5432/postgres?currentSchema=project0
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.utilities.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repositories.CustomerDAOImpl.login(CustomerDAOImpl.java:123)
	at com.revature.Driver.main(Driver.java:38)
2019-12-20 22:24:49 WARN  ConnectionUtil:23 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.utilities.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repositories.CustomerDAOImpl.login(CustomerDAOImpl.java:123)
	at com.revature.Driver.main(Driver.java:38)
2019-12-20 22:25:55 WARN  ConnectionUtil:23 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for postgresql://localhost:5432/postgres
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.utilities.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repositories.CustomerDAOImpl.login(CustomerDAOImpl.java:123)
	at com.revature.Driver.main(Driver.java:38)
2019-12-20 22:29:16 WARN  ConnectionUtil:23 - Unable to obtain connection to database
java.sql.SQLException: No suitable driver found for postgresql://localhost:5432/
	at java.sql.DriverManager.getConnection(Unknown Source)
	at java.sql.DriverManager.getConnection(Unknown Source)
	at com.revature.utilities.ConnectionUtil.getConnection(ConnectionUtil.java:21)
	at com.revature.repositories.CustomerDAOImpl.login(CustomerDAOImpl.java:123)
	at com.revature.Driver.main(Driver.java:38)
2019-12-23 03:16:15 INFO  Driver:18 - PROGRAM START
2019-12-23 03:16:29 WARN  Driver:50 - WARNING: SQLException occurred.
2019-12-23 03:16:48 WARN  Driver:50 - WARNING: SQLException occurred.
2019-12-23 03:17:13 WARN  Driver:186 - WARNING: SQLException occurred.
2019-12-23 03:20:18 INFO  Driver:18 - PROGRAM START
